project:
  type: website
jupyter: julia-1.10  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "Package version: `0.2.0`"

format:
  html: 
    toc: true


website:
  
  title: "browndriverbriggs"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials/index.qmd          
      - text: "Concepts"
        file: concepts/index.qmd   
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  
            
    right:   
      - icon: github
        href: https://github.com/neelsmith/BrownDriverBriggs.jl
        aria-label: GitHub
      - icon: person-circle
        menu:
          - text: "About me"
            href: https://neelsmith.quarto.pub
          - text: "More of my digital scholarship"
            href: https://neelsmith.quarto.pub/digschol/
        aria-label: "More of my work"
        
  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd
        - tutorials/bdb.qmd
        - tutorials/strong.qmd
        - tutorials/bdbplus.qmd
        
        
        
    - title: "Guides"
      contents:
        - guides/index.qmd
        - guides/pos.qmd
       
        
    - title: "Reference"
      contents: 
        - reference/index.qmd
        - reference/bdb.qmd
        - reference/strong.qmd
        - reference/bdbplus.qmd
        




    - title: "Concepts"
      contents: 
        - concepts/index.qmd
      
        

    - title: "Home"
      contents:
        - index.qmd               
 

           